version: '3'
services:
  web:
    build: 
      context: .  # folder
      dockerfile: Dockerfile.dev  # name of build file to use


    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules   # bookmark
      - .:/app              # volume to map

  tests:
    build: 
      context: .  
      dockerfile: Dockerfile.dev

    volumes: 
      - /app/node_modules
      - .:/app
    
    command: ["npm", "run", "test"] # override starting command